# Generated by Django 4.2.6 on 2023-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=30)),
                ('launch_year', models.CharField(max_length=50)),
            ],
        ),
    ]
